#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: generic

sudo: false

# http://docs.travis-ci.com/user/apt/
addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - gcc-4.8
            - libboost1.55-dev
            - libboost-program-options1.55-dev
            - libgdal1-dev
            - libgeos-dev
            - pandoc
            - sqlite3

#-----------------------------------------------------------------------------

matrix:
  include:

    # 1/ Linux Clang Builds

    - os: linux
      compiler: linux-clang36-release
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['clang-3.6', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='clang++-3.6' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-clang37-dev
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.6', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['clang-3.6', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='clang++-3.6' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-clang38-release
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['clang-3.8', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='clang++-3.8' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-clang38-dev
      addons:
        apt:
          sources: ['llvm-toolchain-precise-3.8', 'ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['clang-3.8', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='clang++-3.8' BUILD_TYPE='Dev'


    # 2/ Linux GCC Builds
    - os: linux
      compiler: linux-gcc48-release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-4.8', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-4.8' COMPILER_FLAGS='-Wno-return-type' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-gcc48-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-4.8', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-4.8' COMPILER_FLAGS='-Wno-return-type' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-gcc49-release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-4.9', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-4.9' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-gcc49-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-4.9', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-4.9' BUILD_TYPE='Dev'


    - os: linux
      compiler: linux-gcc5-release
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-5', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-5' BUILD_TYPE='Release'

    - os: linux
      compiler: linux-gcc5-dev
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-5', 'libboost1.55-all-dev', 'pandoc']
      env: COMPILER='g++-5' BUILD_TYPE='Dev'


    # 3/ OSX Clang Builds
    - os: osx
      osx_image: xcode6.4
      compiler: xcode64-clang-release
      env: COMPILER='clang++' BUILD_TYPE='Release'

    - os: osx
      osx_image: xcode6.4
      compiler: xcode64-clang-dev
      env: COMPILER='clang++' BUILD_TYPE='Dev'


    - os: osx
      osx_image: xcode7
      compiler: xcode7-clang-release
      env: COMPILER='clang++' BUILD_TYPE='Release'

    - os: osx
      osx_image: xcode7
      compiler: xcode7-clang-dev
      env: COMPILER='clang++' BUILD_TYPE='Dev'

#-----------------------------------------------------------------------------

install:
  - git clone --quiet --depth 1 https://github.com/osmcode/libosmium.git ../libosmium
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake boost || true
    fi
  - cmake --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - CXX=${COMPILER} CXXFLAGS=${COMPILER_FLAGS} cmake -LA .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

script:
  - make VERBOSE=1 && ctest --output-on-failure

#-----------------------------------------------------------------------------
